name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
jobs:
  accessibility-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Install HTTP Server
        run: npm install -g http-server
      - name: Start Local Server
        run: |
          http-server ./build -p 8080 &  
          sleep 5
      - name: Install AXE CLI
        run: npm install @axe-core/cli -g

      - name: Install Chrome driver
        run: npx browser-driver-manager install chrome -y

      - name: Evaluate accessibility
        run: axe http://localhost:8080 --exit

      - name: Stop Local Server
        run: pkill http-server || true
