name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
jobs:
  accessibility-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Install HTTP Server
        run: npm install -g http-server
      - name: Start Local Server
        run: |
          http-server ./build -p 8080 &  
          sleep 5
      - name: Evaluate accessibility
        # uses: trongduc2206/accessibility-hub-runner@91d23232898b98ad478ff988bb5a9f882f983ae8
        uses: trongduc2206/accessibility-hub-runner@622980486761c392e73b596b9357bb1655ce8e91
        with:
          url: 'http://localhost:8080'
          service_id: 'testservice14582'
      - name: Stop Local Server
        run: pkill http-server || true
